### Evaluation de la fréquence de résonance


In [1]:
import plotly
import plotly.graph_objs as go
from numpy import *

def induct2(R_app, cap2,frequence):
    """
        input: charge, valeur C_2 fréquence
        return: Calcule la valeur de l'inductance 2 
    """
    return (R_app**2 * cap2)/(1+(frequence*2*pi*cap2*R_app)**2)

def frequ_resonance(L2,cap2,R_app):
    """
        input: 
        return: La fréquence de résonance
    """
    return sqrt(1/(cap2*L2) - 1/(cap2*R_app)**2)/(2*pi)

def induct1(cap1, frequency):
    """
        input: la fréquence désirée et une capacité
        return: la valeur de l'inductance 1
    """
    return 1/((2*pi*frequency)**2*cap1)

def turn_count(induct, R):
    return sqrt((2*induct)/(4*pi**2 * 1e-7 * R))

def induct_length(n_count, R):
    return N*2*pi*R
 

cap = [1e-6, 1e-7, 1e-8, 1e-9]
R_app = 100
L2 = 55e-6
i = linspace(1000,100000, 1e4)

data = []

for cap_value in cap:
    print(frequ_resonance(L2,cap_value,R_app))
    data.append(go.Scatter(x=i, y=induct2(R_app, cap_value,i), name="L2 C= {}F".format(cap_value)) )
    
for cap_value in cap:
    data.append(go.Scatter(x=i, y=induct1(cap_value,i), name="L1 C= {}F".format(cap_value)) )
    
plotly.offline.plot({
    "data": data,
    "layout": go.Layout(title="Inductance in function of frequency")
}, filename="induct_func_frequency.html")

/home/thatthetheos/.local/lib/python2.7/site-packages/ipykernel_launcher.py:36: DeprecationWarning:

object of type <type 'float'> cannot be safely interpreted as an integer.

/home/thatthetheos/.local/lib/python2.7/site-packages/ipykernel_launcher.py:17: RuntimeWarning:

invalid value encountered in sqrt



21401.350544926845
65971.24667817901
143961.06266350442
nan


'induct_func_frequency.html'

### Evaluation de la fréquence ne sortie de l'ampli Op

$$f = \dfrac{1}{2*R_3 * C_1 *ln(2)}$$


In [46]:
from numpy import *
import plotly
import plotly.graph_objs as go

def frequency(C1,R):
    return 1/(2*R*C1*log(2))

R = linspace(100,10000,10000)
freq = frequency(R,0.000001)
cap = [1e-6, 1e-7, 1e-8, 1e-9]

data = []
for cap_value in cap:
    data.append(go.Scatter(x=R, y=frequency(cap_value,R), name="With C = {}".format(cap_value)))
                
plotly.offline.plot({
    "data": data,
    "layout": go.Layout(title="Frequency of the oscillator")
}, filename="frequency.html")

'frequency.html'

### Evaluation de $Z_{equi}$
$$Z_{equi}= \frac{\omega^2 M^2 R_L + \omega^2 M^2 R_2 + \omega^4 M^2 C_2^2 R_L^2 R_2 + \omega^3M^2j(-\omega^2L_2C_2^2R_L^2+C_2R_L^2-L_2)}{(R_2 + R_L -\omega^2 C_2 L_2 R_L)^2 + (\omega C_2 R_L R_2 + \omega L_2)^2}$$


$$ Re(Z_{equi}) = \dfrac{(\omega \cdot M)^2 \cdot (R_l + R_2 + (\omega\cdot R_l \cdot C_2)^2 \cdot R_2)}{(R_2 + R_l - \omega^2 \cdot C_2 \cdot L_2\cdot R_l)^2 + (\omega \cdot C_2 \cdot R_l\cdot R_2 + \omega \cdot L_2)^2 }$$

In [12]:
i = linspace(1000,100000, 1e4)
frequence = i 
omega = 2 * pi * frequence#fréquence
R_l = 100.0 #Resistance de la charge au secondaire
R_2 = 1.0# Resistance de l'inductance secondaire
C_1 = 1e-6#Capacité du primaire
C_2 = 1e-6#Capacité du secondaire
L_2 = induct2(R_l, C_2,frequence) #Inductance du secondaire
L_1 = induct1(C_1 , frequence) #Inductan au primaire 
V_s = 5.0#Tension d'entrée au primaire
R_th = 1.0#Restance equivalent de la source de tension
R_1 =  0.8#Résistance de l'inductance 1
k = 0.4
M = k * sqrt(L_1 * L_2)#inductance mutuelle


#Z_equi = ((omega*M)**2 * (R_l + R_2 + (omega*R_l*C_2)**2 * R_2))/ ((R_2 + R_l - omega**2 * C_2 * L_2*R_l)**2 + (omega*C_2*R_l*R_2 + omega*L_2)**2 )
data = []
#P = (Z_equi * V_s **2 ) / (2*(Z_equi + R_1 + R_th))
for cap_val_1 in cap:
    for cap_val_2 in cap:
        C_1 = cap_val_1
        C_2 = cap_val_2
        L_2 = induct2(R_l, C_2, frequence) #Inductance du secondaire
        L_1 = induct1(C_1, frequence) #Inductan au primaire
        M = k * sqrt(L_1 * L_2)
        
        #Z_sec = R_2 + R_l/(1+(R_l*omega*C_2)**2)
        
    
        Z_equi = ((omega*M)**2 * (R_l + R_2 + (omega*R_l*C_2)**2 * R_2))/ ((R_2 + R_l - omega**2 * C_2 * L_2*R_l)**2 + (omega*C_2*R_l*R_2 + omega*L_2)**2 )
    
        
        alpha2 = R_l /(R_l + R_2)
        P = alpha2 * (Z_equi * V_s **2 ) / (2*(Z_equi + R_1 + R_th)**2)
        print(P)
        data.append(go.Scatter(x=frequence, y=array(P), name="a2 C1 {} , C2 {}".format(cap_val_1, cap_val_2)))
        data.append(go.Scatter(mode = 'markers',x = array(frequence[argmax(P)]),y = array(amax(P))))
         
        P =  (Z_equi * V_s **2 ) / (2*(Z_equi + R_1 + R_th)**2)
        data.append(go.Scatter(mode = 'markers',x = array(frequence[argmax(P)]),y = array(amax(P))))
        data.append(go.Scatter(x=frequence, y=array(P),  name="a1 C1 {} , C2 {}".format(cap_val_1, cap_val_2)))

#data = [go.Scatter(x=frequence, y=array(P)),go.Scatter(x=frequence, y=L_1),go.Scatter(x=frequence, y=L_2)]
print(induct1(1e-6 , 19000))
print(induct2(R_l, 1e-8,19000))

plotly.offline.plot({
    "data": data,
    "layout": go.Layout(title="Frequency of the oscillator")
}, filename="Power_frequency.html")


/home/thatthetheos/.local/lib/python2.7/site-packages/ipykernel_launcher.py:1: DeprecationWarning:

object of type <type 'float'> cannot be safely interpreted as an integer.



[0.63191693 0.63195586 0.63199518 ... 1.01518911 1.01506368 1.01493826]
[1.71192524 1.71192516 1.71192507 ... 1.6320034  1.63198298 1.63196255]
[0.51118403 0.51118403 0.51118402 ... 0.50951543 0.5095151  0.50951478]
[0.05946088 0.05946088 0.05946088 ... 0.0594586  0.0594586  0.0594586 ]
[0.07667123 0.07667704 0.0766829  ... 1.47813958 1.4782464  1.4783532 ]
[0.62997831 0.6299787  0.62997909 ... 0.81020951 0.81024229 0.81027507]
[1.71192947 1.71192947 1.71192947 ... 1.7114973  1.71149721 1.71149713]
[0.5111842  0.5111842  0.5111842  ... 0.51116746 0.51116745 0.51116745]
[0.00782517 0.00782578 0.00782639 ... 0.28638956 0.28644005 0.28649054]
[0.07638234 0.07638239 0.07638245 ... 0.10529597 0.10530165 0.10530732]
[0.62995891 0.62995891 0.62995892 ... 0.63191615 0.63191654 0.63191693]
[1.71192951 1.71192951 1.71192951 ... 1.71192525 1.71192524 1.71192524]
[0.00078412 0.00078419 0.00078425 ... 0.03102315 0.03102909 0.03103502]
[0.00779508 0.00779509 0.00779509 ... 0.01083075 0.01083135 0.01

'Power_frequency.html'

## Evaluation de la puissance en respectant $Z_{eq} = R_{1} + R_{th}$
$P = \dfrac{V^2}{8\cdot (R_1 + R_{th})}$

In [39]:
max_P = V_s**2/ (8*(R_1+R_th))
yP = max_P * ones(len(frequence))
data.append(go.Scatter(x=frequence, y=yP))

### Plotly

In [3]:
plotly.offline.plot({
    "data": data,
    "layout": go.Layout(title="Frequency of the oscillator")
}, filename="Power_frequency.html")


'Power_frequency.html'

### Verification du graphs pour la condition d'opitmisation
Sans considerer $\alpha_2$

$Z_{equi} = R_1 + R_{th}$

In [44]:

R_l = 75
R_2 = 1
f = 43524.75
L_1 = induct1(1e-6, f)
L_2 = induct2(R_l, 1e-6, f)

print(L_1)
print(L_2)
C_1 = 1e-6
C_2 = 1e-6


omega = 2*pi*f
M = 0.4 * sqrt(L_1 * L_2)

Z_equi = ((omega*M)**2 * (R_l + R_2 + (omega*R_l*C_2)**2 * R_2))/ ((R_2 + R_l - omega**2 * C_2 * L_2*R_l)**2 + (omega*C_2*R_l*R_2 + omega*L_2)**2 )
        
        
print(Z_equi)

print(R_1 + R_th)




1.33711171156e-05
1.33394081753e-05
1.8120214003068944
1.8


Nous pouvons observer que les valeurs calculées respectent bien la condition.

### En considérant $\alpha_2$
$Z_{equi} = R_1 + R_{th}$


In [33]:
R_l = 75
R_2 = 1
L_1 = induct1(1e-7, 258639.3)
L_2 = induct2(R_l, 1e-6, 258639.3)
C_1 = 1e-7
C_2 = 1e-6
f = 258639.3

omega = 2*pi*f
M = sqrt(L_1 * L_2)

Z_equi = ((omega*M)**2 * (R_l + R_2 + (omega*R_l*C_2)**2 * R_2))/ ((R_2 * R_l - omega**2 * C_2 * L_2*R_2)**2 + (omega*C_2*R_l*R_2 + omega*L_2)**2 )

Z_sec = R_2 + R_l/(1+(R_l*omega*C_2)**2)
alpha2 = R_l / Z_sec

print(Z_equi)

print(R_1 + R_th)
print(alpha2)

3.7673414562015504
1.8
74.6232658544


IL y a un problème: Alpha 2 est bcp plus grand que 1

## Evaluation de l'impédance du circuit secondaire
### Inductance = Source de tension
On considère l'inductance comme source de tension et on néglige la valeur de la résistance interne de fil.

Le circuit se résume donc à une capacité et une charge en parrallèle

$Z = \dfrac{R_l}{R_l \cdot j \cdot \omega \cdot C_2 + 1}$

$Z- \dfrac{R_l \cdot (1-R_l^2 \cdot j \cdot \omega \cdot C_2)}{1 + (R_l \cdot \omega \cdot C_2)^2}$

$Im(Z) = -\dfrac{R_l ^2 \cdot \omega \cdot C_2}{1+(R_l \cdot \omega \cdot C_2)^2}$

$Re(Z) = \dfrac{R_l}{1 + (R_l \cdot \omega \cdot C_2)^2}$


On a un problème avec ce modèle ci car si on annule la partie imaginaire on doit avoir $R_l^2\cdot \omega \cdot C_2 = 0$ 


### On considère l'impédance de l'inductance

même circuit que précedemment mais en ajoutant l'impédance de l'inductance en serie avec le circuit parrallèle

on obtient

$Z = j \cdot \omega \cdot L_2 + \dfrac{R_l}{R_l \cdot j \cdot \omega \cdot C_2 + 1}$

$Z = j \cdot \omega \cdot L_2 + \dfrac{R_l \cdot (1-R_l^2 \cdot j \cdot \omega \cdot C_2)}{1 + (R_l \cdot \omega \cdot C_2)^2}$

$Im(Z) = \omega L_2 - \dfrac{R_l^2 \omega C_2}{1+(R_l \omega C_2)^2}$

Ce qui donne la relation suivante
$\omega = \sqrt{\dfrac{R_l^2 C_2 - L_2}{L_2 R_l^2 C_2^2}}$ que nous utilison déja pour déduire la valeur de l'inductance 2

$Re(Z) = \dfrac{R_l}{1+(R_l \omega C_2)^2}$

Cette partie a l'air correcte cfr https://www.electronics-tutorials.ws/accircuits/parallel-circuit.html et https://www.electronics-tutorials.ws/accircuits/parallel-resonance.html

### Optimisation de la puissance:
$P = \alpha_2 \cdot \dfrac{Z_{equi}\cdot V_s^2}{2\cdot (Z_{equi}+R_1+R_{th})^2}$

et

$\alpha_2 = \dfrac{R_l \cdot ( 1 + (R_l \cdot \omega \cdot C_2)^2)}{R_2 + R_l}$


En Dérivant
$P = \dfrac{Z_{equi}\cdot V_s^2}{2\cdot (Z_{equi}+R_1+R_{th})^2}$

par rapport à $Z_{equi}$ on obtient:

$\dfrac{\delta}{\delta Z_{equi}}( P )= \dfrac{\delta}{\delta Z_{equi}}( \dfrac{Z_{equi}\cdot V_s^2}{2\cdot (Z_{equi}+R_1+R_{th})^2}) = 0$


$Z_{equi} = R_1 + R_{th}$

Il faut donc respecter cette deuxième condition pour optimiser le transfert de puisssance. Nous pouvons substituer dans l'expression de la puissance $Z_{equi}$ par $R_1 + R_{th}$
afin d'obtenir l'expression suivante:

$P = \dfrac{V^2}{8\cdot (R_1 + R_{th})}$

$Z_{equi} = \dfrac{\omega \cdot M^2 \cdot (R_l + R_2 + (\omega \cdot R_l \cdot C_2)^2 \cdot R_2)}{(R_2 \cdot R_l - \omega^2 \cdot C_2 \cdot L_2\cdot R_2)^2 + (\omega \cdot C_2 \cdot R_l \cdot R_2 + \omega \cdot L_2)^2}$

Et 

$M = k \cdot \sqrt{L_1 \cdot L_2}$

Et 

$\omega = 2\cdot \pi \cdot f$

En Considérant, pour imposer la résonance

$ L_1 = \dfrac{1}{(2\cdot \pi \cdot f)^2 \cdot C_1}$

Et
$ L_2 = \dfrac{R_l^2 \cdot C_2}{1+(f\cdot 2\cdot \pi \cdot C_2 \cdot R_l)^2}$

Nous obtenons finalement un expression pour la puissance:

$P = \dfrac{R_l \cdot ( 1 + (R_l \cdot 2\cdot \pi \cdot f \cdot C_2)^2)}{R_2 + R_l} \cdot \frac{\dfrac{2\cdot \pi \cdot f \cdot M^2 \cdot (R_l + R_2 + (2\cdot \pi \cdot f \cdot R_l \cdot C_2)^2 \cdot R_2)}{(R_2 \cdot R_l - (2\cdot \pi \cdot f)^2 \cdot C_2 \cdot \dfrac{R_l^2 \cdot C_2}{1+(f\cdot 2\cdot \pi \cdot C_2 \cdot R_l)^2} \cdot R_2)^2 + (2\cdot \pi \cdot f \cdot C_2 \cdot R_l \cdot R_2 + 2\cdot \pi \cdot f \cdot \dfrac{R_l^2 \cdot C_2}{1+(f\cdot 2\cdot \pi \cdot C_2 \cdot R_l)^2})^2} \cdot V_s^2}{2\cdot (\dfrac{2\cdot \pi \cdot f \cdot M^2 \cdot (R_l + R_2 + (2\cdot \pi \cdot f \cdot R_l \cdot C_2)^2 \cdot R_2)}{(R_2 \cdot R_l - (2\cdot \pi \cdot f)^2 \cdot C_2 \cdot \dfrac{R_l^2 \cdot C_2}{1+(f\cdot 2\cdot \pi \cdot C_2 \cdot R_l)^2}\cdot R_2)^2 + (2\cdot \pi \cdot f \cdot C_2 \cdot R_l \cdot R_2 + 2\cdot \pi \cdot f \cdot \dfrac{R_l^2 \cdot C_2}{1+(f\cdot 2\cdot \pi \cdot C_2 \cdot R_l)^2})^2} + R_1 +R_{th})^2}$